def cfgAppend(cfg, prefix):
    r = cfg.copy()
    for key in cfg:
        try:
            #join strings, append lists
            if type(cfg[key]) == type(""):
                r[key] = prefix[key] + cfg[key]
            else:
                r[key] = prefix[key] + cfg[key]
        except:
            #key prolly doesn't exist
            continue
    return r

def cfgPrint(cfg, prefix="    "):
    for key in cfg:
        print prefix + key + " = ", cfg[key]

def cfgBuild(cfg, type):
    env = Environment(CCFLAGS = cfg["ccflags"])
    obj = 0;
    usr = "..\\..\\usr\\"
    if type == "StaticLibrary" or type == "SharedLibrary":
        if type == "StaticLibrary":
            obj = env.StaticLibrary(target=cfg["name"], source=cfg["sources"], CPPPATH=cfg["includePaths"], LIBPATH=cfg["libPaths"], LIBS=cfg["libs"])
        if type == "SharedLibrary":
            obj = env.SharedLibrary(target=cfg["name"], source=cfg["sources"], CPPPATH=cfg["includePaths"], LIBPATH=cfg["libPaths"], LIBS=cfg["libs"])
        env.Install(usr+"lib", obj)
        for header in (cfg["headers"]):
            Command(usr+"include\\"+header, header, Copy("$TARGET", "$SOURCE"))
    if type == "Program":
        obj = env.Program (target=cfg["name"], source=cfg["sources"], CPPPATH=cfg["includePaths"], LIBPATH=cfg["libPaths"], LIBS=cfg["libs"])
        env.Install(usr+"bin", obj)
    return obj

def build (cfgs, type, cfgName):
    r = {}
    r["cfg"] = cfgAppend(cfgs["default"], cfgs[cfgName])
    r["obj"] = cfgBuild(r["cfg"], type)
    return r

cfgMotorsportSim = {
    "default": {
        "name": "motorsportSim"
        ,"includePaths": Split("/usr/include/boost-1_33_1")
        ,"libPaths": Split(" ")
        ,"libs": Split(" ")
        ,"sources": Split("motorsport.cpp")
        ,"headers": Split("motorsport.h")
        ,"ccflags": " -Wall -Wextra -pedantic"
        }
    ,"debug": {
        "name":"d"
        ,"ccflags": "-g"
        }
    ,"release": {
        }
    }
motorsportSim = build(cfgMotorsportSim, "StaticLibrary", "debug");
#motorsportSim = build(cfgMotorsportSim, "SharedLibrary", "debug");
#motorsportSim = build(cfgMotorsportSim, "Program", "debug");
#cfgPrint(motorsportSim["cfg"], "mosp.")
cfgMotorsport = {
    "default": {
        "name": "motorsport"
        ,"includePaths": Split("/usr/include/boost-1_33_1")
        ,"libPaths": Split(".")
        ,"libs": [motorsportSim["obj"], Split("boost_program_options-gcc-mt")]
        ,"sources": Split("main.cpp")
        ,"headers": Split(" ")
        ,"ccflags": " -Wall -Wextra -pedantic"
        }
    ,"debug": {
        "name":"d"
        ,"ccflags": "-g "
        }
    ,"release": {
        }
    }
motorsport = build(cfgMotorsport, "Program", "debug");
#cfgPrint(motorsport["cfg"], "tests.")