import os

#first part of scons path
pwd = os.getenv("PWD")

#detect if current OS follows Filesystem Hierarchy Standard
fhs = pwd[:1] == "/"
sep = "/"

if not fhs:
    sep = "\\"

def cfgAppend(cfg, prefix):
    r = cfg.copy()
    for key in cfg:
        try:
            #join strings, append lists
            if type(cfg[key]) == type(""):
                r[key] = cfg[key] + prefix[key]
            else:
                r[key] = cfg[key] + prefix[key]
        except:
            #key prolly doesn't exist
            continue
    return r

def cfgPrint(cfg, prefix="    "):
    for key in cfg:
        print prefix + key + " = ", cfg[key]

def cfgBuild(cfg, type):
    env = Environment(CCFLAGS = cfg["ccflags"])
    obj = 0;
    usr = "."+sep;
    if type == "StaticLibrary" or type == "SharedLibrary":
        if type == "StaticLibrary":
            obj = env.StaticLibrary(target=cfg["name"], source=cfg["sources"], CPPPATH=cfg["includePaths"], LIBPATH=cfg["libPaths"], LIBS=cfg["libs"])
        if type == "SharedLibrary":
            obj = env.SharedLibrary(target=cfg["name"], source=cfg["sources"], CPPPATH=cfg["includePaths"], LIBPATH=cfg["libPaths"], LIBS=cfg["libs"])
        env.Install(usr+"lib", obj)
        for header in (cfg["headers"]):
            dir = usr+"include"+sep+""
            #Command(dir+header, header, Copy("$TARGET", "$SOURCE"))
    if type == "Program":
        obj = env.Program (target=cfg["name"], source=cfg["sources"], CPPPATH=cfg["includePaths"], LIBPATH=cfg["libPaths"], LIBS=cfg["libs"])
        env.Install(usr+"bin", obj)
    return obj

def build (cfgs, type, cfgName):
    r = {}
    r["cfg"] = cfgAppend(cfgs["default"], cfgs[cfgName])
    r["obj"] = cfgBuild(r["cfg"], type)
    return r

cfgSim = {
    "default": {
        "name": "Motorsport-sim"
        ,"includePaths": Split("include /usr/include /usr/include/boost /usr/include/boost-1_33_1")
        ,"libPaths": Split("lib ")
        ,"libs": Split(" ")
        ,"sources": Split("src/Sim.cpp ")
        ,"headers": Split("Sim.h ")
        ,"ccflags": "-Wall -Wextra -Wno-deprecated "
        }
    ,"debug": {
        "name":"D"
        ,"ccflags": "-g"
        }
    ,"release": {
        }
    }
#sim = build(cfgSim, "StaticLibrary", "debug");
sim = build(cfgSim, "SharedLibrary", "debug");
#cfgPrint(core["cfg"], "sim.")
cfgMain = {
    "default": {
        "name": "motorsport-sim"
        ,"includePaths": [sim["cfg"]["includePaths"],
                          Split("include ../../deps/testsoon/include")]
        ,"libPaths": Split("lib ")
        ,"libs": [sim["obj"],
                  Split(" ")]
        ,"sources": Split("src/main.cpp")
        ,"headers": Split(" ")
        ,"ccflags": "-Wall -Wextra "
        }
    ,"debug": {
        "name":"D"
        ,"ccflags": "-g "
        }
    ,"release": {
        }
    }
main = build(cfgMain, "Program", "debug");
#cfgPrint(main["cfg"], "main.")
